// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteFrame.Data;

namespace TesteFrame.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210827234914_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("TesteFrame.Data.Vitrine", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<byte[]>("Imagem")
                        .HasColumnType("longblob");

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Codigo");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Codigo = 1,
                            Descricao = "Maçã",
                            Nome = "Maçã",
                            Quantidade = 10,
                            Valor = 2m
                        },
                        new
                        {
                            Codigo = 2,
                            Descricao = "Banana",
                            Nome = "Banana",
                            Quantidade = 10,
                            Valor = 4m
                        },
                        new
                        {
                            Codigo = 3,
                            Descricao = "Manga",
                            Nome = "Manga",
                            Quantidade = 10,
                            Valor = 3m
                        },
                        new
                        {
                            Codigo = 4,
                            Descricao = "Morango",
                            Nome = "Morango",
                            Quantidade = 10,
                            Valor = 6m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
